export const GET_COUNTRIES = "GET_COUNTRIES"
export const DELETE_COUNTRIES = "DELETE_COUNTRIES";
export const ADD_COUNTRY = "ADD_COUNTRY"
export const GET_SINGLE_COUNTRY = "GET_SINGLE_COUNTRY"
export const UPDATE_COUNTRY = "UPDATE_COUNTRY"